name: Testing9999
favicon: null
layout_spectrum: 0.98559
typography_spectrum: 0.96842
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030116'
    - '#3b364a'
    - '#908492'
    - '#b8b5ca'
  brandStrength: 1
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0.3912876201793551
purpose: []
