name: Testing9999
favicon: null
layout_spectrum: 0.78912
typography_spectrum: 0.534238307736814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030116'
    - '#3b364a'
    - '#908492'
    - '#b8b5ca'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.39128762017935514
purpose: []
